REMOVE_FROM_BEGINNING_OF_TITLES = ["a ", "an ", "the ", "\\["]
COLLECTIONS = ["1A: Text & Symbol", "1: Primary", "2: Reference", "3: Copyright"]
ACQUISITION_TYPES =  ["Gift", "Thrift/Secondhand Store", "Free Book Exchange", "Flea Market", "Used Book Store", "Library Sale", "Internet", "Antique Store", "Found Item", "Street/Stoop/Garage Sale", "Scout Purchase"]
WORK_TYPES = ["Book", "Collage", "Digital Animation", "Drawing", "Inkjet Print", "Installation", "Mixed Media", "Painting", "Play", "Sculpture", "Weaving"]
SUBJECT_AUTHORITIES = ["LCSH"]
DIGITAL_ASSET_SUBJECT_AUTHORITIES = ["LCSH"]
USER_ROLES = ["administrator", "cataloger", "image cataloger", "guest"]
CATALOGER_ROLES = ["administrator", "cataloger", "image cataloger"]
SAVE_UNPUBLISHED_TEXT = "save item but don't publish"
SAVE_PUBLISHED_TEXT = "save item"
PUBLISH_TEXT = "save and publish"
UNPUBLISH_TEXT = "save and unpublish"