
development:
  adapter: postgresql
  encoding: unicode
  database: reanimation_library
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: reanimation_library_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: reanimation_library
  pool: 5
  username:
  password:
