# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ :name => 'Chicago' ) { :name => 'Copenhagen' }])
#   Mayor.create(:name => 'Daley', :city => cities.first)

ImageColor.find_or_create_by_name("Black &amp; White" )
ImageColor.find_or_create_by_name("Color" )
ImageColor.find_or_create_by_name("Mixed Color and Black &amp; White" )
ImageColor.find_or_create_by_name("Two-Tone" )

ImageType.find_or_create_by_name("Architectural Diagrams" )
ImageType.find_or_create_by_name("Bowling Diagrams" )
ImageType.find_or_create_by_name("Braille" )
ImageType.find_or_create_by_name("Cartographic Material" )
ImageType.find_or_create_by_name("Chess Game Diagrams" )
ImageType.find_or_create_by_name("Color Chart" )
ImageType.find_or_create_by_name("Echocardiograph" )
ImageType.find_or_create_by_name("Fingerprints" )
ImageType.find_or_create_by_name("Golf Diagrams" )
ImageType.find_or_create_by_name("Graphic Design Patterns" )
ImageType.find_or_create_by_name("Illustration" )
ImageType.find_or_create_by_name("Information Graphic" )
ImageType.find_or_create_by_name("International Phoentic Alphabet" )
ImageType.find_or_create_by_name("Line Drawing" )
ImageType.find_or_create_by_name("Logarithmic Table" )
ImageType.find_or_create_by_name("Mathematic Notation" )
ImageType.find_or_create_by_name("Mathematical Diagrams" )
ImageType.find_or_create_by_name("Medical Diagram" )
ImageType.find_or_create_by_name("Micrograph" )
ImageType.find_or_create_by_name("Musical Notation" )
ImageType.find_or_create_by_name("Needlepoint Patterns" )
ImageType.find_or_create_by_name("Photograph" )
ImageType.find_or_create_by_name("Photo Illustration" )
ImageType.find_or_create_by_name("Radiograph" )
ImageType.find_or_create_by_name("Sewing Patterns" )
ImageType.find_or_create_by_name("Shorthand Notation" )
ImageType.find_or_create_by_name("Spectograph" )
ImageType.find_or_create_by_name("Technical Diagrams" )
ImageType.find_or_create_by_name("Text Only" )
ImageType.find_or_create_by_name("Two-Tone" )
ImageType.find_or_create_by_name("Typography" )
ImageType.find_or_create_by_name("Weather Symbols" )
ImageType.find_or_create_by_name("Woodcuts")
